services:
  backend:
    container_name: backend
    depends_on:
      - database
    volumes:
      - ./logs/:/logs/:rw
    environment:
      - ENV=DOCKER
      - DB_PASS=test
      - DB_ADDRESS=database
    build:
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:81:3000
    healthcheck:
      test: curl -X GET --fail https://0.0.0.0:80/api/health -Is --insecure || exit 1
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 2s
