services:
  database:
    container_name: database
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - ${DATABASE_PORT}:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 5s
      retries: 10
      start_period: 10s
    volumes:
      - database-data:/var/lib/postgresql/data
  backend:
    container_name: backend
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./logs/:/logs/:rw
    environment:
      ENV: DOCKER
      # database address is hardcoded into URL to override .env
      DATABASE_URL: postgres://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@database:${DATABASE_PORT}/${DATABASE_NAME}
      MIGRATE: ${MIGRATE}
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - 0.0.0.0:${BACKEND_PORT}:3000
    healthcheck:
      test: curl -X GET --fail https://0.0.0.0:3000/api/health -Is --insecure || exit 1
      interval: 10s
      timeout: 1s
      retries: 5
      start_period: 2s

volumes:
  database-data: {}
